ece459_1151/urls.py
from django.conf.urls import patterns, url

from ece459_1151 import views

urlpatterns = patterns('',
    url(r'^(?P<slug>\w+)/$', views.assignment, name='assignment'),
)

ecegit/urls.py
# Copyright 2014-2016 Jonathan Eyolfson
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', 'ecegit.views.home', name='home'),
    url(r'^setup/$', 'ecegit.views.setup', name='setup'),
    url(r'^commits_csv/$', 'ecegit.views.commits_csv', name='commits_csv'),
    url(r'^profile/', include('django_ssh.urls', namespace='ssh')),
    url(r'^repo/', include('django_gitolite.urls', namespace='git')),
    url(r'^login/$', 'django_cas.views.login', name='login'),
    url(r'^logout/$', 'django_cas.views.logout', name='logout'),
    url(r'^subscribe/(?P<repo_id>\d+)/$', 'ecegit.views.subscribe',
        name='subscribe'),
    url(r'^unsubscribe/(?P<repo_id>\d+)/$', 'ecegit.views.unsubscribe',
        name='unsubscribe'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ece459/1151/', include('ece459_1151.urls', namespace='ece459_1151')),
)

templates/ece459/assignment.html
{% extends "base.html" %}

{% block content %}

{% if is_student %}
  {% if not group %}
<h1>Register Group</h1>

{% if register_error %}
<div class="alert alert-danger">{{ register_error }}</div>
{% endif %}

<p>
  <form class="form-inline" role="form" action="{% url 'ece459:assignment' 'a3' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
      <label class="sr-only" for="username">Username</label>
      <input type="text" class="form-control" name="username" placeholder="Username">
    </div>
    <button class="btn btn-default" type="submit" name="partner">Partner</button>
  </form>
</p>
<hr />
<p>
  <form role="form" action="{% url 'ece459:assignment' 'a3' %}" method="post" name="solo">
    {% csrf_token %}
    <button class="btn btn-default" type="submit" name="solo">Solo</button>
  </form>
</p>
  {% else %}
<h1>Group</h1>

<dl class="dl-horizontal">
  <dt>ID</dt>
  <dd>{{ group.pk }}</dd>
  <dt>Repository</dt>
  <dd>{{ group.repo }}</dd>
</dl>

    {% if testbot_messages %}
<h2>Testbot Messages</h2>

<ul class="list-group">
      {% for message in testbot_messages %}
  <li class="list-group-item">{{ message }}</li>
      {% endfor %}
</ul>
    {% endif %}
  {% endif %}
{% endif %}

{% if tsp_results %}
<h1>Leaderboard</h1>

<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Group</th>
        <th>Iterations</th>
        <th>Distance</th>
      </tr>
    </thead>
    <tbody>
{% for result in tsp_results %}
      <tr>
        <td>{{ result.group.pk }}</td>
        <td>{{ result.iterations }}</td>
        <td>{{ result.distance }}</td>
      </tr>
{% endfor %}
    </tbody>
  </table>
</div>
{% endif %}

{% endblock %}